### ISSUE TITLE
Expenses ratio is not available for this asset and source

### ISSUE THREAD

**Issue by brunomalone** [joseballester/muFunds#1]
Hello. I get this :
Error: Expenses ratio is not available for this asset and source. Please try another data source (línea 104).

I tried with all the different sources, but the problem remains... The ISIN is this: LU0389812347 , is a very popular fund for european bogleheads.

Thanks for your amazing work!

**Comment by joseballester** [comment]
Hi Bruno, thank you for your feedback!

It's true that the expenses ratio is not available when using the generic Morningstar source, but it works with country-specific sites (at least Austria, Belgium, Germany and Spain). Just try calling:

``
=muFunds("expenses", "LU0389812347", "morningstar-at")
``

Let me know if it works for you!
