### ISSUE TITLE
ISIN not working

### ISSUE THREAD

**Issue by gosugimoto** [joseballester/muFunds#11]
I've got most other funds working in google sheets, but this one:
Legal & General International Index Trust Class C - Accumulation
Just doesn't seem to propagate and errors all the time.  I've tried both ISIN and morningstar URL id..

Any ideas...

**Comment by joseballester** [comment]
Hi @gosugimoto! Thank you for opening this issue and sorry for the delay. 

It seems that this fund doesn't work properly with the Morningstar generic mode, which is the one used by default when the `source` argument is empty (more info [here](https://www.mufunds.com/usage.html)).

I just tried using Morningstar UK instead: `=muFunds("nav", "GB00BG0QP604", "morningstar-gb")` and it works properly for all options. Let me know your thoughts!

**Comment by gosugimoto** [comment]
Brilliant, thank you!!!!!
--
iamgo.net
