### ISSUE TITLE
Unable to retrieve nav for iShares fund from morningstar-gb

### ISSUE THREAD

**Issue by atanaskanchev** [joseballester/muFunds#3]
Trying to import [iShares Global Property Securities Equity Index Fund (UK) D Acc](http://www.morningstar.co.uk/uk/funds/snapshot/snapshot.aspx?id=F00000OJRZ) using `=muFunds("nav", "F00000OJRZ", "morningstar-gb")`

Getting error `TypeError: No se puede llamar al método "getDescendants" de undefined. (line 33).`

**Comment by atanaskanchev** [comment]
http://quotes.morningstar.com/fund/c-header?t=F00000OJRT doesn't return nav

**Comment by joseballester** [comment]
Hi @atanaskanchev, thank you for your feedback! This was an important bug that have been affecting many UK funds lately. Fortunately, the issue has now been solved in commit [`da170dc7ba03e4ef81644b8040a74f12cf82e0b6`](https://github.com/joseballester/muFunds/commit/da170dc7ba03e4ef81644b8040a74f12cf82e0b6) (Bugfixes for Morningstar UK) and the bugfix will be incorporated to the next µFunds release, v2.2.

> http://quotes.morningstar.com/fund/c-header?t=F00000OJRT doesn't return nav

Regarding this issue, it is out of our hands as the data is just retrieved from Morningstar. As an alternative, we recommend you using the `morningstar-gb` source (that you were already trying to use) that will be working once µFunds v2.2 is accepted in the Google Sheets add-on store.

**Comment by joseballester** [comment]
µFunds v2.2 is now published and should appear updated in your Google Sheets spreadsheet.

**Comment by brunomalone** [comment]
I'm having the same issue now with morningstar-es 
`=muFunds("nav"; "0P0000MLIH"; "morningstar-es")`
I guess is morningstar fault.

**Comment by joseballester** [comment]
Hi @brunomalone, thanks for your feedback! I just tested your commands and for me it works fine. Sometimes (don't know why) Morningstar pages return an error, but it shouldn't be common. If the error persists, let me know please.

By the way, I see that you want to follow an ETF from Amsterdam, I would suggest using the Google Finance function instead, as it will give you the NAV throughout the whole day and not only the closing NAV as Morningstar does: `=googlefinance("AMS:IWDA")`.

See the [compatibility list](https://mufunds.com/compatibility.html) for more details.
