### ISSUE TITLE
ReferenceError: Xml is not defined (línea 100).

### ISSUE THREAD

**Issue by CESGA** [joseballester/muFunds#32]
Hola Jose,

Al cargar el código de MuFunds en una hoja de google spreadsheet me da ese error en las celdas en las que utilizo las funciones. Es como si el "Xml.parse(xmlstr, true)" no estuviese funcionando. Sin embargo, si utilizo el complemento de MuFunds, si que me funciona. 

Te agradezco la ayuda,
Un saludo,

**Comment by joseballester** [comment]
Hola @CESGA,

El error que comentas aparece porque el nuevo runtime de Google Apps Script, V8, no contempla el uso de la clase `Xml` y en su defecto recomienda usar `XmlService` ([más información aquí](https://developers.google.com/apps-script/guides/v8-runtime/migration#avoid_xml_literals_and_the_xml_object)).

Sin embargo, por lo poco que he podido probar, `XmlService` da muchos problemas al parsear etiquetas propias de HTML que no son XML estándar, y por tanto no es tan sencillo como simplemente sustituir `Xml` por `XmlService`.

Actualmente µFunds sigue utilizando el runtime antiguo, Rhino, que sí incluye la clase `Xml`. Para hacer lo mismo con tu propio script de Google Apps Script, puedes ir al menú de tu proyecto y seleccionar **Run > Disable new Apps Script runtime powered by Chrome V8**. A partir de entonces, tu proyecto usará Rhino y no deberías tener problemas en utilizar la clase `Xml`.

Cualquier cosa, me comentas!
