### ISSUE TITLE
Can't import fund data from quefondos

### ISSUE THREAD

**Issue by Goeamon** [joseballester/muFunds#34]
I'm really appreciated that you present this excellent&easy formula. But I have a problem that may be you can help me know what's problem
1.) I try this formula with this =muFunds("nav,LU1997245508,https://www.quefondos.com/es/fondos/ficha/index.html?isin=LU1997245508"). But the result show this context "#ERROR! You have selected an invalid option. Do I have to install any code first to make it work?
2.) Is this formula gonna work with Bloomberg too?
Thank you

**Comment by joseballester** [comment]
Hi @Goeamon, thanks for your issue!

Regarding 1), the correct formula would be `=muFunds("nav", "LU1997245508", "quefondos")`. Note that:
- You must separate each argument not only with `,` but with `", "` (if that doesn't work you may be using comma as a decimal separator, and then you should use `"; "`).
- You only have to name the source `"quefondos"`, but not the entire URL.

Regarding 2), right now Bloomberg is not compatible with µFunds and does not appear in our [Compatibility list](https://mufunds.com/compatibility.html).

I will close the issue as there is no actual issue, but let me know if you need anything else!
