### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by stocklord** [joseballester/muFunds#60]
Hi, trying to pull two Vanguard UK funds into Google sheets but for both get the error message

"Error: you have selected an invalid option. (line 16)."

The entries are on lines 17 and 18, but the error for each references 16, which is a different stock and is correct.

I am using nav,morningstar ID, morningstar-uk (or - gb), neither work.

**Comment by stocklord** [comment]
Same issue for every fund I try, nothing seems to work.

**Comment by stocklord** [comment]
Jose, is this site now out of use?

**Comment by joseballester** [comment]
Hi @stocklord, sorry for the delay but I try to answer as soon as possible in my free time. 

The line 16 that appears in the error message refers to the line in the µFunds code in which the exception/error is thrown, so it won't help us to troubleshoot the issue.

Could you please share exactly what formula are you using? Are you using `"nav"` within double quotes, as in `=muFunds("nav", "identifier", "morningstar")`?

**Comment by stocklord** [comment]
Hi Jose
All working now, I wasn't using double quotation marks. There is nothing at all on the 'usage and examples' page that mentions quotation marks, maybe it should have been obvious to me, but i'm not a programmer.

Thanks for your help.

**Comment by stocklord** [comment]
Hi Jose
I'm using your formula for two fund price. I'm now finding another issue: three or four times a day for one or both, but not simultaneously, price reverts to 'ERROR' and I have to retype the formula, which then works.
A real pain, any ideas?
