### ISSUE TITLE
Error Función desconocida: 'muFunds'.

### ISSUE THREAD

**Issue by ofaofaofa** [joseballester/muFunds#64]
Hola @joseballester , al parecer google sheets dejo de reconocer el complemento.
Muchas gracias por la ayuda.

**Comment by joseballester** [comment]
¡Hola, @ofaofaofa! ¿Puede ser que estés intentando usar el complemento en una nueva hoja de cálculo? Puedes asegurarte de que el complemento está activado para tu documento siguiendo las instrucciones del apartado "Activate µFunds in a spreadsheet (following uses)" de [esta página](https://mufunds.com/install.html#:~:text=Activate%20%C2%B5Funds%20in%20a%20spreadsheet%20(following%20uses)).

**Comment by ofaofaofa** [comment]
Muchas gracias!! Ya lo solucione.

Ricardo O'Farrell

El 1 ene 2024, a la(s) 14:25, Jose Ballester ***@***.***> escribió:

﻿

¡Hola, @ofaofaofa<https://github.com/ofaofaofa>! ¿Puede ser que estés intentando usar el complemento en una nueva hoja de cálculo? Puedes asegurarte de que el complemento está activado para tu documento siguiendo las instrucciones del apartado "Activate µFunds in a spreadsheet (following uses)" de esta página<https://mufunds.com/install.html#:~:text=Activate%20%C2%B5Funds%20in%20a%20spreadsheet%20(following%20uses)>.
