### ISSUE TITLE
Error de análisis de fórmula

### ISSUE THREAD

**Issue by Blasmadull** [joseballester/muFunds#7]
Hola josebaseller.
Instalo el complemento, lo activo y cuando introduzco la fórmula en cualquier celda siempre aparece ese error. 
He probado con dos parámetros, con tres, con referencia al ISIN, poniendo el ISIN como cadena...
Nada, no hay manera de obtener el precio del fondo ni siquiera con el ejemplo.

Por cierto los ejemplos tienen una pinta estupenda. Gracias, me parece un trabajo genial.

**Comment by joseballester** [comment]
Hola @Blasmadull, gracias por tus comentarios!

¿Podrías indicarme qué formula estás usando? Es posible que, si usas la coma `,` como separador de decimales en tu hoja de cálculo, tengas que usar el punto y coma `;` para separar los argumentos cuando llames a la función `muFunds`. Por ejemplo, deberías usar `=muFunds("nav"; "LU0996179007")` para obtener el valor liquidativo del fondo [Amundi Index Solutions S&P 500 AE-C](http://www.morningstar.es/es/funds/snapshot/snapshot.aspx?id=F00000T7PZ).

**Comment by Blasmadull** [comment]
Gracias @joseballester, ha funcionado estupendamente.
Era eso, utilizar punto y coma ; para separar los parámetros de la función.
Ahora funciona estupendamente
